from reportlab.platypus import (

    SimpleDocTemplate,

    Paragraph,

    Spacer
)

from reportlab.lib.styles \
    import getSampleStyleSheet

import io

def create_report(
        model_name,
        dataset_name,
        problem_type,
        metrics,
        training_time,
        cv_score,
        hyperparameters,
        sample_count,
        feature_count
):

    buffer = io.BytesIO()

    pdf = SimpleDocTemplate(
        buffer
    )

    styles = \
        getSampleStyleSheet()

    content = []
    
    content.append(

        Paragraph(

            "MLPilot Studio Report",

            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )
    
    content.append(

        Paragraph(

            "Dataset Information",

            styles["Heading2"]
        )
    )

    content.append(

        Paragraph(

            f"<b>Dataset:</b> {dataset_name}",

            styles["Normal"]
        )
    )

    content.append(

        Paragraph(

            f"<b>Samples:</b> {sample_count}",

            styles["Normal"]
        )
    )

    content.append(

        Paragraph(

            f"<b>Features:</b> {feature_count}",

            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 15)
    )
    
    content.append(

        Paragraph(

            "Model Information",

            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 10)
    )
    
    content.append(

        Paragraph(

            f"<b>Model:</b> "
            f"{model_name}",

            styles["Normal"]
        )
    )
    
    content.append(

        Paragraph(

            f"<b>Problem Type:</b> "
            f"{problem_type}",

            styles["Normal"]
        )
    )
    
    content.append(

        Paragraph(

            f"<b>Training Time:</b> "
            f"{training_time:.2f}s",

            styles["Normal"]
        )
    )
    
    cv_display = (
            round(cv_score, 4)
            if cv_score is not None
            else "N/A"
        )
    
    content.append(

        Paragraph(

            f"<b>CV Score:</b> "
            f"{cv_display}",

            styles["Normal"]
        )
    ) 

    content.append(
        Spacer(1, 20)
    )

    content.append(

        Paragraph(

            "Hyperparameters",

            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 10)
    )
    
    

    for param, value in hyperparameters.items():

        content.append(

            Paragraph(

                f"<b>{param}</b>: {value}",

                styles["Normal"]
            )
        )  
        
    content.append(
        Spacer(1, 20)
    )

    content.append(

        Paragraph(

            "Performance Metrics",

            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 10)
    )
    
    for k, v in metrics.items():

        if k in [
            "Confusion Matrix",
            "Classification Report"
        ]:
            continue

        if isinstance(v, float):

            v = f"{v:.4f}"

        else:

            v = str(v)

        content.append(

            Paragraph(

                f"<b>{k}</b>: {v}",

                styles["Normal"]
            )
        )
        
    if "Classification Report" in metrics:

        content.append(
            Spacer(1, 15)
        )

        content.append(

            Paragraph(

                "Classification Report",

                styles["Heading2"]
            )
        )

        report_text = str(
            metrics["Classification Report"]
        )

        report_text = report_text.replace(
            "\n",
            "<br/>"
        )

        content.append(

            Paragraph(

                report_text,

                styles["Code"]
            )
        )
        
    if "Confusion Matrix" in metrics:

        content.append(
            Spacer(1, 15)
        )

        content.append(

            Paragraph(

                "Confusion Matrix",

                styles["Heading2"]
            )
        )

        cm = str(
            metrics["Confusion Matrix"]
        )

        cm = cm.replace(
            "\n",
            "<br/>"
        )

        content.append(

            Paragraph(

                cm,

                styles["Code"]
            )
        )
        
    content.append(
        Spacer(1, 25)
    )

    content.append(

        Paragraph(

            "Generated by MLPilot",

            styles["Italic"]
        )
    )
        
    pdf.build(content)

    buffer.seek(0)

    return buffer